# Generated by Django 4.1.7 on 2023-05-03 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='featured_product',
        ),
        migrations.CreateModel(
            name='Sub_collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('featured_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ShopApp.product')),
                ('parent_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='ShopApp.collection')),
            ],
        ),
    ]
