# Generated by Django 4.1.2 on 2023-06-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('K', 'Kids')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='taille',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
