# Generated by Django 4.1.2 on 2023-05-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_clothes_kids',
        ),
        migrations.DeleteModel(
            name='product_clothes_men',
        ),
        migrations.DeleteModel(
            name='product_clothes_women',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
