# Generated by Django 4.1.2 on 2023-06-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_alter_clothes_gender_alter_product_taille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('K', 'Kids')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='taille',
            field=models.CharField(blank=True, default='s, m, l', max_length=255),
            preserve_default=False,
        ),
    ]
