# Generated by Django 4.1.7 on 2023-05-03 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_remove_collection_featured_product_sub_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_collection',
            name='featured_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ShopApp.sub_collection'),
        ),
        migrations.AlterField(
            model_name='sub_collection',
            name='parent_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcollections', to='ShopApp.collection'),
        ),
    ]
