# Generated by Django 4.2.1 on 2023-05-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_remove_product_image_alter_proimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images'),
        ),
    ]
