# Generated by Django 4.1.2 on 2023-03-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
