# Generated by Django 4.1.7 on 2023-05-03 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0003_remove_sub_collection_featured_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ShopApp.product')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('K', 'Kids')], max_length=1)),
            ],
            bases=('ShopApp.product',),
        ),
    ]
