# Generated by Django 4.1.2 on 2023-03-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0010_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discount_percentage', models.IntegerField()),
                ('level', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default=29000, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='date_end',
            field=models.DateField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='date_start',
            field=models.DateField(default=2023),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_method', models.CharField(choices=[('Poste', 'Poste'), ('Yalidine', 'Yalidinr')], max_length=255)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('shipping_date', models.DateField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ShopApp.order')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.address')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(max_length=255)),
                ('rating', models.CharField(max_length=5)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ShopApp.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ShopApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_methode', models.CharField(choices=[('carte edahabia', 'carte edahabia'), ('cash on delivery', 'cash on delivery')], max_length=255)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ShopApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='favList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ShopApp.customer')),
                ('items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ShopApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='club_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.club')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.customer')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Product_variation',
            field=models.ManyToManyField(to='ShopApp.product_variation'),
        ),
    ]
