# Generated by Django 4.1.2 on 2023-03-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0011_club_remove_orderitem_product_address_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='shipping_method',
            field=models.CharField(choices=[('Poste', 'Poste'), ('Yalidine', 'Yalidine')], max_length=255),
        ),
    ]
